version: "3.7"
services:
  postgres:
    image: postgis/postgis:12-3.3 
    environment:
      - POSTGRES_DB=$DB_DATABASE
      - POSTGRES_PASSWORD=$DB_USERNAME
      - POSTGRES_USER=$DB_PASSWORD
    restart: always
    volumes:
      - "./mlflow-db:/var/lib/postgresql/data"

  mlflow:
    image: mlflow:test 
    environment:
      - DB_HOSTNAME=$DB_HOSTNAME
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_REGION=$AWS_REGION
    restart: always
    depends_on:
      - postgres
        # command: tail -f /dev/null
    ports:
      - "5000:5000"
    command: >
      mlflow server --backend-store-uri postgresql://$DB_USERNAME:$DB_PASSWORD@$DB_HOSTNAME/$DB_DATABASE
      --host 0.0.0.0
      --default-artifact-root $ARTIFACT_STORE
    
